#ifndef PROTOCOL_H
#define PROTOCOL_H

#define MSG_HEAD_LEN 4
#define MAX_MSG_LEN (10 * 1024 * 1024)
#define CHUNK_SIZE 4096

enum CommandType {
    CMD_REGISTER = 1,
    CMD_LOGIN = 2,
    CMD_LOGOUT = 3,
    CMD_TOKEN_REFRESH = 4,
    CMD_HEARTBEAT = 5,

    CMD_UPLOAD_INIT = 10,
    CMD_UPLOAD_CHUNK = 11,
    CMD_UPLOAD_FINISH = 12,
    CMD_UPLOAD_PROGRESS = 13,
    CMD_UPLOAD_PAUSE = 14,
    CMD_UPLOAD_RESUME = 15,

    CMD_FILE_LIST = 20,
    CMD_FILE_DELETE = 21,
    CMD_FILE_INFO = 22,

    CMD_VIDEO_LIST = 30,
    CMD_VIDEO_LIKE = 31,
    CMD_VIDEO_PLAY = 32,
    CMD_VIDEO_RECOMMEND = 33,

    CMD_GIF_LIST = 40,
    CMD_GIF_UPLOAD = 41,

    CMD_STREAM_START = 50,
    CMD_STREAM_STOP = 51,
    CMD_STREAM_LIST = 52,

    CMD_RESP_BASE = 1000,
    CMD_REGISTER_RESP = 1001,
    CMD_LOGIN_RESP = 1002,
    CMD_HEARTBEAT_RESP = 1005,
    CMD_TOKEN_REFRESH_RESP = 1004,
    CMD_UPLOAD_INIT_RESP = 1010,
    CMD_UPLOAD_CHUNK_RESP = 1011,
    CMD_UPLOAD_FINISH_RESP = 1012,
    CMD_FILE_LIST_RESP = 1020,
    CMD_VIDEO_LIST_RESP = 1030,
    CMD_VIDEO_LIKE_RESP = 1031,
    CMD_VIDEO_PLAY_RESP = 1032,
    CMD_VIDEO_RECOMMEND_RESP = 1033,
    CMD_GIF_LIST_RESP = 1040,
    CMD_STREAM_LIST_RESP = 1052
};

#endif
